# Generated by Django 4.2.3 on 2023-07-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='inventory',
        ),
    ]
